### PR TITLE
added Equilibrium Moisture Content (EMC) calculation to emonTH output

### PR DESCRIPTION
**Pull request by solarmill**
Hi!  We've added an extra channel to our emonTH system to calculate Equilibrium Moisture Content (EMC) from the measured Temperature and Humidity values.  We've using this to measure the curing of wood that will be used as a raw material for product manufacturing, and we think EMC data could be useful to other emonTH users.  If you're interested, please feel free to incorporate our code into the core emonTH repository, or let us know if you think there are any changes that should be made.

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks, yes I'm sure this branch will be useful for some users

**Comment by glynhudson** [comment]
Hi, I just had to undo the merge of this pull request since it seems you didn't make a new branch for EMC. The pull request merged into the master branch! Please could you re-submit with a new branch or just a folder added with EMC code. Thanks. Keep up the good work :)

**Comment by solarmill** [comment]
Hi Glyn,

I think this pull request was from a local branch: "origin/emc".  Isn't it up to you where in the main repository it is merged into, not me?  I'm new to branching and merging, so I'm happy to be corrected if I'm wrong.  Thanks, 

Andy

**Comment by glynhudson** [comment]
Do you think I would need to create a new branch and switch to this new branch before merging? However I think it's less confusion to just have the one branch and a new folder called EMC with your code. What do you think?

**Comment by solarmill** [comment]
Yes, that sounds perfect.   So you'll be including an EMC folder in the master version by default?

**Pull request merged**
